/**:
  ros__parameters:
    fcu_url: "/dev/ttyACM0:115200"  # Uprav dle portu/rychlosti
    gcs_url: ""
    target_system_id: 1
    target_component_id: 1
    fcu_protocol: "v2.0"
    system_id: 255
    component_id: 240
    plugin_allowlist:
      - command          # Nutné pro příkazy a dotaz na verzi FCU
      - sys_status       # Systémový stav a Heartbeat
      - sys_time         # Synchronizace času
      - landing_target   # Vlastní target plugin
    mav_frame: "BODY_FRD"
