services:
  drc_rover_container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drc_rover_container
    restart: unless-stopped
    
    # Síť a IPC
    network_mode: host
    ipc: host
    shm_size: '512m'
    
    # Přístup k hardwaru (sériové porty pro FCU, USB kamery, GPIO)
    privileged: true
    
    volumes:
      # Mapování zdrojového kódu (případně celého ws)
      - ../../src/drone_follow:/workspace/src/drone_follow:rw
      - ../../src/rover_drone_following:/workspace/src/rover_drone_following:rw
      - ../../src/rover_mavlink_communication:/workspace/src/rover_mavlink_communication:rw
      - ../../src/rover_navigation:/workspace/src/rover_navigation:rw
      #- ../../src/opencv_vision:/workspace/src/opencv_vison:rw
      
      # Přístup ke všem zařízením v /dev (ttyACM, ttyUSB, video*, i2c, spi)
      - /dev:/dev:rw
      # Zachování systémového času z hostitele (důležité pro časové značky zpráv)
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      
    environment:
      - ROS_DOMAIN_ID=67
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      # Zajištění nebufferovaného výstupu z logů
      - RCUTILS_LOGGING_BUFFERED_STREAM=1
      - RCUTILS_COLORIZED_OUTPUT=1

    # Udrží kontejner běžící na pozadí pro připojení přes docker exec
    command: tail -f /dev/null
