#ifndef ROVER_MAVLINK_COMMUNICATION__MODE_CONTROL_HPP_
#define ROVER_MAVLINK_COMMUNICATION__MODE_CONTROL_HPP_

enum class RoverControlMode
{
    UNKNOWN,
    MANUAL,
    GUIDED,
    HOLD,
    AUTO
};

#endif  // ROVER_MAVLINK_COMMUNICATION__MODE_CONTROL_HPP_
